#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common

teeOutput

echo "Checking config version"

if [ ${FPPVERSION} -lt 10 ]
then
	echo "$0: Unable to upgrade FPP below Alpha 0.1.0, please upgrade your SD image"
	exit 1
fi

export FPPVERSION

########################################################################

if [ -f ${CFGVERSIONFILE} ]
then
	CFGVERSION=$(cat ${CFGVERSIONFILE})
fi

echo "FPP Version: ${FPPVERSION}"
echo "Config Version: ${CFGVERSION}"



FPPPLATFORM=$(cat /etc/fpp/platform 2> /dev/null)
case "${FPPPLATFORM}" in
    'BeagleBone Black')
        if [ ! -e "/usr/include/arm-linux-gnueabihf/libswresample/swresample.h" ]; then
	     apt-get update
             apt-get  -q -y --reinstall install libsdl2-dev libavcodec-dev libavformat-dev libswresample-dev
        fi
    ;;
esac

for VERSION in $(seq 1 1000)
do
	if [ ${VERSION} -gt ${CFGVERSION} ]
	then
		if [ -f "${UPGRADEDIR}/${VERSION}/upgrade.sh" ]
		then
			echo "Upgrading config to version ${VERSION}"
			(cd ${UPGRADEDIR}/${VERSION} && ./upgrade.sh)
			CFGVERSION=${VERSION}
			echo ${VERSION} > ${CFGVERSIONFILE}
		else
			echo "Up to date at config version ${CFGVERSION}"
			exit 0
		fi
	fi
done


